# Generated by Django 5.2 on 2025-05-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='checkout_request_id',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
    ]
