# Generated by Django 5.2 on 2025-04-18 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='about_us_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(default='CoreNet Services', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='founded_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mission_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='companyprofile',
            table='company_profile',
        ),
    ]
